# Generated by Django 6.1.1 on 2026-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('intended_purpose', models.TextField()),
                ('config_text', models.TextField()),
                ('blast_radius', models.CharField(max_length=20)),
                ('attack_paths', models.JSONField(default=list)),
                ('mitigations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
