# Generated by Django 6.1.1 on 2026-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(max_length=500)),
                ('agent_name', models.CharField(max_length=200)),
                ('intended_purpose', models.TextField(blank=True)),
                ('score', models.IntegerField()),
                ('band', models.CharField(max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('impact_paths', models.JSONField(default=list)),
                ('findings', models.JSONField(default=list)),
                ('mitigation_candidates', models.JSONField(default=list)),
                ('graph_dot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
